START:MOV P1,#0FFH
ACALL ONESECDELAY
MOV P1,#0FH
ACALL ONESECDELAY
LJMP START


ONESECDELAY:MOV R6,#40
DELAYLOOP: 
	  ACALL DELAY
      DJNZ R6,DELAYLOOP
      LJMP NEXT2
DELAY: MOV TMOD,#00000001B 
       MOV TH0,#3CH
       MOV TL0,#0B0H 
       SETB TR0 
HERE: JNB TF0,HERE 
      CLR TR0 
      CLR TF0 
      RET
	  NEXT2:RET
END